server:
  port: 8081

spring:
  application:
    name: spring-boot-ehcache-demo
  
  # Spring Cache 配置
  cache:
    type: jcache
    # 启用XML配置
    jcache:
      config: classpath:ehcache.xml

# 日志配置
logging:
  level:
    root: INFO
    com.example.ehcache: DEBUG
    org.springframework.cache: DEBUG