server:
  port: 8989  # 从8881修改为8989
  servlet:
    context-path: /kafka-demo

# 激活额外的Kafka配置文件
spring:
  profiles:
    active: kafka
  
  # Thymeleaf配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true