server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  # activiti 配置
  activiti:
    # 配置为 false 则每次应用启动不检查 Activiti 数据表是否存在及版本号是否匹配，提升应用启动速度
    database-schema-update: true
    # 在项目单独作为一个引擎，本身不部署流程的时候，如果resources目录没有“processes”目录，启动项目报错–找不到processes目录。
    # 需要在配置文件中添加以下内容：
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
    #    process-definition-location-suffixes:
    #      - **.bpmn
    #      - **.bpmn20.xml
    #保存历史数据级别设置为 full 最高级别，便于历史数据的追溯
    history-level: full