SET FOREIGN_KEY_CHECKS=0;
drop table act_evt_log;
drop table act_ge_bytearray;
drop table act_ge_property;
drop table act_hi_actinst;
drop table act_hi_attachment;
drop table act_hi_comment;
drop table act_hi_detail;
drop table act_hi_identitylink;
drop table act_hi_procinst;
drop table act_hi_taskinst;
drop table act_hi_varinst;
drop table act_id_group;
drop table act_id_info;
drop table act_id_membership;
drop table act_id_user;
drop table act_procdef_info;
drop table act_re_deployment;
drop table act_re_model;
drop table act_re_procdef;
drop table act_ru_event_subscr;
drop table act_ru_execution;
drop table act_ru_identitylink;
drop table act_ru_job;
drop table act_ru_task;
drop table act_ru_variable;
commit;