server:
  port: 8081
  servlet:
    context-path: /data-jpa

# 应用名称
spring:
  application:
    name: data-jpa

  # 引入本地配置
  config:
    import: classpath:application-mysql.yml

  # JPA/Hibernate配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# OpenAPI配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

# 日志配置
logging:
  level:
    root: INFO
    com.github.zhuyizhuo.datajpa: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE