# 应用基本配置
spring:
  application:
    name: dingtalk-message-demo
  profiles:
    active: dev, dingtalk
  main:
    allow-bean-definition-overriding: true

# 服务器配置
server:
  port: 8082
  servlet:
    context-path: /dingtalk

# 日志配置
logging:
  level:
    com.github.zhuyizhuo.dingtalk.demo: INFO
    com.aliyun.dingtalk: INFO