spring:
  rabbitmq:
    host: 127.0.0.1
    port: 14807
    username: admin
    password: pwd
#    virtual-host: /
#    listener:
#      simple:
#        acknowledge-mode: manual # 手动应答
#        concurrency: 5 # 消费端最小并发数
#        max-concurrency: 10 # 消费端最大并发数
#        prefetch: 5 # 一次请求中预处理的消息数量
#    cache:
#      channel:
#        size: 50 # 缓存的channel数量
#    publisher-confirms: true # 发送成功回掉
#    publisher-returns: true
#    stomp-port: 14809